// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALVvIdZsN8RXN0cFDIe0Bxb4U37PeYR04',
    appId: '1:837295446432:web:8dc9639f2842d48db0ecc5',
    messagingSenderId: '837295446432',
    projectId: 'skillboost-c846b',
    authDomain: 'skillboost-c846b.firebaseapp.com',
    storageBucket: 'skillboost-c846b.appspot.com',
    measurementId: 'G-E7YGC9EQGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsrRqDbrpvTMg6UmxbjQmIC67zqBtNmCE',
    appId: '1:837295446432:android:d8fa068c012aa253b0ecc5',
    messagingSenderId: '837295446432',
    projectId: 'skillboost-c846b',
    storageBucket: 'skillboost-c846b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByvPIZedFX1GcUhknFZOdq1BgCAlsQeyA',
    appId: '1:837295446432:ios:161108861e4daf07b0ecc5',
    messagingSenderId: '837295446432',
    projectId: 'skillboost-c846b',
    storageBucket: 'skillboost-c846b.appspot.com',
    iosBundleId: 'com.example.skillBoost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByvPIZedFX1GcUhknFZOdq1BgCAlsQeyA',
    appId: '1:837295446432:ios:161108861e4daf07b0ecc5',
    messagingSenderId: '837295446432',
    projectId: 'skillboost-c846b',
    storageBucket: 'skillboost-c846b.appspot.com',
    iosBundleId: 'com.example.skillBoost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALVvIdZsN8RXN0cFDIe0Bxb4U37PeYR04',
    appId: '1:837295446432:web:f4c27b9e3b400343b0ecc5',
    messagingSenderId: '837295446432',
    projectId: 'skillboost-c846b',
    authDomain: 'skillboost-c846b.firebaseapp.com',
    storageBucket: 'skillboost-c846b.appspot.com',
    measurementId: 'G-VBWJ9YS0SK',
  );
}
